services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: elections
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user                    
      MYSQL_PASSWORD: user
    volumes:
      - ./mysql/init-db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/custom-entrypoint.sh:/usr/local/bin/custom-entrypoint.sh
      - db-data:/var/lib/mysql
    restart: always 
    ports:
      - 3307:3306
    entrypoint: /usr/local/bin/custom-entrypoint.sh
  
  harris-scraper:
    build:
      context: scraper/
      dockerfile: ./Dockerfile
    image: elections_producer_1
    container_name: harris_scraper
    ports:
      - "5001:5001"
    environment:
      - CANDIDATE=KamalaHarris
      - FB_EMAIL=${FB_EMAIL_HARRIS}
      - FB_PASSWORD=${FB_PASSWORD_HARRIS}
    command: sh -c "sleep 15s ; python3 -u scraper.py"
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_started

  trump-scraper:
    build:
      context: scraper/
      dockerfile: ./Dockerfile
    image: elections_producer_2
    container_name: trump_scraper
    ports:
      - "5002:5002"
    environment:
      - CANDIDATE=DonaldTrump
      - FB_EMAIL=${FB_EMAIL_TRUMP}
      - FB_PASSWORD=${FB_PASSWORD_TRUMP}
    command: sh -c "sleep 15s ; python3 -u scraper.py"
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_started

  restarter:
      image: docker:cli
      container_name: restarter
      volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
      command: ["/bin/sh", "-c", "while true; do sleep 3000; docker stop trump_scraper harris_scraper; sleep 600; docker start trump_scraper harris_scraper; done"]
      restart: unless-stopped

volumes:
  db-data: