services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: elections
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user                    
      MYSQL_PASSWORD: user
    volumes:
      - ./mysql/init-db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/custom-entrypoint.sh:/usr/local/bin/custom-entrypoint.sh
      - db-data:/var/lib/mysql
    restart: always 
    ports:
      - 3307:3306
    entrypoint: /usr/local/bin/custom-entrypoint.sh
  
  harris-scraper:
    build:
      context: harris-scraper/
      dockerfile: ./Dockerfile
    image: elections_producer_1
    container_name: harris_scraper
    ports:
      - "5001:5001"
    env_file:
    - ./.env
    restart: on-failure
    stop_grace_period: 5m
    command: sh -c "sleep 15s ; python3 -u scraper.py"
    depends_on:
      mysql:
        condition: service_started

  trump-scraper:
    build:
      context: trump-scraper/
      dockerfile: ./Dockerfile
    image: elections_producer_2
    container_name: trump_scraper
    ports:
      - "5002:5002"
    env_file:
    - ./.env
    restart: on-failure
    stop_grace_period: 5m
    command: sh -c "sleep 15s ; python3 -u scraper.py"
    depends_on:
      mysql:
        condition: service_started

  restarter:
      image: docker:cli
      container_name: restarter
      volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
      command: ["/bin/sh", "-c", "while true; do sleep 3600; docker restart trump_scraper harris_scraper; done"]
      restart: unless-stopped

volumes:
  db-data: